### ISSUE TITLE
HP | SDE Intern | Presencial | Tlaquepaque

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [Proyecto-Nutria/MX-Internships#16]
### Link a la publicación del Internship

https://jobs.hp.com/jobdetails/18391763/software-application-developer-intern-tlaquepaque-mx/

### Nombre de la compañía

HP

### Título del Internship

SDE Intern

### Lugar

Tlaquepaque

### ¿En qué temporada es el internship?

Winter 2024, Spring 2024

### ¿La posición necesita saber inglés?

Yes

### ¿El internship está recibiendo aplicaciones actualmente?

Yes

### Email asociado a tu cuenta de GitHub (opcional)

davidlazaro20@hotmail.com

**Comment by akotadi** [comment]
This already exists
