### ISSUE TITLE
Didi | Business Analysis Intern | Presencial | CDMX

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [Proyecto-Nutria/MX-Internships#17]
### Link a la publicación del Internship

https://careers-didiglobal.icims.com/jobs/10115/job?utm_source=indeed_integration&iis=Job+Board&iisn=Indeed&indeed-apply-token=73a2d2b2a8d6d5c0a62696875eaebd669103652d3f0c2cd5445d3e66b1592b0f

### Nombre de la compañía

Didi

### Título del Internship

Business Analysis Intern

### Lugar

Ciudad De México

### ¿En qué temporada es el internship?

Winter 2024, Spring 2024

### ¿La posición necesita saber inglés?

Yes

### ¿El internship está recibiendo aplicaciones actualmente?

Yes

### Email asociado a tu cuenta de GitHub (opcional)

davidlazaro20@hotmail.com

**Comment by akotadi** [comment]
"Error: The requested job could not be found."
