### ISSUE TITLE
New Internship at Oracle

### ISSUE THREAD

**Issue by SoyAngelHdez** [Proyecto-Nutria/MX-Internships#20]
### Link a la publicación del Internship

https://careers.oracle.com/jobs/#en/sites/jobsearch/job/199622/?utm_medium=jobshare

### Nombre de la compañía

Oracle

### Título del Internship

Software Developer Intern

### Lugar

Zapopan, Jalisco

### ¿En qué temporada es el internship?

Summer 2024

### ¿La posición necesita saber inglés?

Yes

### ¿El internship está recibiendo aplicaciones actualmente?

Yes

### Email asociado a tu cuenta de GitHub (opcional)

hdezhernandezangel@gmail.com

### Notas extra (opcional)

This is a great option for people who like low level programming and for Mexican people who want to stay in the country while living a programming internship.

**Comment by akotadi** [comment]
Can you change the title to "Software Developer Intern" and the location to "Zapopan, Jalisco" pls?

**Comment by SoyAngelHdez** [comment]
Done in the original comment, should I make a new Issue or its fine?
