### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by OscarSantosMu** [Proyecto-Nutria/MX-Internships#5]
### Link a la publicación del Internship

https://www.riotgames.com/en/work-with-us/job/5330414/software-engineering-intern-los-angeles-usa

### Nombre de la compañía

Riot Games

### Título del Internship

Software Engineering Intern

### Lugar

Remoto

### ¿En qué temporada es el internship?

Summer 2024

### ¿La posición necesita saber inglés?

Yes

### ¿El internship está recibiendo aplicaciones actualmente?

Yes

### Email asociado a tu cuenta de GitHub (opcional)

oscarsantosmu@gmail.com

### Notas extra (opcional)

Publicación adicional: https://www.linkedin.com/posts/markbenliyan_internship-riotgames-coding-activity-7103771809321275392-Gn4J?utm_source=share&utm_medium=member_android

**Comment by akotadi** [comment]
Hola! Este repositorio está enfocado a trabajos en México, igualmente agradecemos tu aporte. 👀

**Comment by akotadi** [comment]
Uy sorry, me confundió cómo explican lo de remoto pero leyendo los FAQs ya vi que sí se puede, gracias por el aporte!
