### ISSUE TITLE
IBM | Blue Journey Intern | Presencial | CDMX

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [Proyecto-Nutria/MX-Internships#6]
### Link a la publicación del Internship

https://careers.ibm.com/job/19021011/mexico-blue-journey-internship-it-program-remote/?codes=SN_LinkedIn&Codes=SN_LinkedIn

### Nombre de la compañía

IBM

### Título del Internship

Blue Journey Internship

### Lugar

Ciudad De México

### ¿En qué temporada es el internship?

Winter 2024, Spring 2024

### ¿La posición necesita saber inglés?

Yes

### ¿El internship está recibiendo aplicaciones actualmente?

Yes

### Email asociado a tu cuenta de GitHub (opcional)

davidlazaro20@hotmail.com

**Comment by akotadi** [comment]
Este internship ya existe, si quieres cambiar algo por favor usa la plantilla para editar :)
